### ISSUE TITLE
Suggestion- check for duplicate tracks

### ISSUE THREAD

**Issue by melissamcewen** [kaylasween/Jammming#2]
(Subtlety)
https://github.com/kaylasween/Jammming/blob/master/src/Components/App/App.js#L23-L29

You might want to create a check to make sure the track isn't already added on this method.  This prevents users from accidentally adding a track multiple times. Though maybe in some cases they might want to do that so this is totally optional.

**Comment by kaylasween** [comment]
added the functionality to check if the track is already in the playlist, and if it is, an alert appears to tell the user the track already exists. Otherwise the track is pushed onto the playlist.

Next steps: to give user the choice to add the duplicated track to the playlist anyway.
